"""mediavocab — reference vocabulary and pydantic data model for media cataloguing.

See `mediavocab_spec.md` for the full design rationale.
"""
from mediavocab.version import __version__

from mediavocab.taxonomy import (
    MediaType,
    VariantKind,
    EntityKind,
    RelationRole,
    CreditSection,
    MembershipStatus,
    ReleaseStatus,
    StreamMode,
    WorkRelationKind,
    ReleaseRelationKind,
    PlaybackModality,
    MEDIA_TYPE_TO_MODALITY,
    infer_modality,
)
from mediavocab.models import (
    EntityRef,
    Membership,
    Credit,
    Appearance,
    Work,
    Release,
    WorkRelation,
    ReleaseRelation,
    Programme,
    Schedule,
    Chapter,
    AccessibilityTrack,
    Entity,
    Conflict,
    ExternalIds,
    Stream,
    License,
    Signals,
    SignalConflict,
    MetadataProvider,
    ProviderMatch,
    ResolutionConflict,
)

__all__ = [
    "__version__",
    "MediaType",
    "VariantKind",
    "EntityKind",
    "RelationRole",
    "CreditSection",
    "MembershipStatus",
    "ReleaseStatus",
    "StreamMode",
    "WorkRelationKind",
    "ReleaseRelationKind",
    "PlaybackModality",
    "MEDIA_TYPE_TO_MODALITY",
    "infer_modality",
    "EntityRef",
    "Membership",
    "Credit",
    "Appearance",
    "Work",
    "Release",
    "WorkRelation",
    "ReleaseRelation",
    "Programme",
    "Schedule",
    "Chapter",
    "AccessibilityTrack",
    "Entity",
    "Conflict",
    "ExternalIds",
    "Stream",
    "License",
    "Signals",
    "SignalConflict",
    "MetadataProvider",
    "ProviderMatch",
    "ResolutionConflict",
]
